version: "3.7"

services:
  mysql:
    image: mysql:8.0.19
    networks:
      - kenmore
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - kenmore
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

# Define networks
networks:
  kenmore:
